version: "3"

services:
  orwell-loraserver:
    image: manglar/orwell:latest
    ports:
      - 8080:8080
  
  postgresql:
    image: postgres:9.6-alpine
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - postgresqldata:/var/lib/postgresql/data

  redis:
    image: redis:4-alpine
    volumes:
      - redisdata:/data

volumes:
  postgresqldata:
  redisdata:

